
import type { Product } from '@/types';

const findImageUrl = (id: string) => {
    // This function is no longer needed as we use direct paths,
    // but we can keep it in case it's used elsewhere or for future needs.
    // For now, it will just return a placeholder path.
    return `/products/${id}.jpg`;
}

// This is now used as fallback data if Firestore is not available.
// The primary source of categories is the 'productCategories' collection in Firestore.
export const categories: string[] = [
  'Active Pharmaceutical Ingredients (APIs)',
  'Excipients',
  'Magnesium Stearate',
  'Other Minerals',
  'Antacids',
];

export const products: Product[] = [
  {
    id: 'paracetamol',
    name: 'Paracetamol (Acetaminophen)',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A widely used over-the-counter analgesic (pain reliever) and antipyretic (fever reducer).',
    specifications: 'Conforms to IP/BP/USP standards. Available in various particle sizes.',
    applications: 'Used in tablets, capsules, and oral suspensions for pain and fever relief.',
    imageUrl: '/products/paracetamol_bottle.jpg',
  },
  {
    id: 'ibuprofen',
    name: 'Ibuprofen',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A nonsteroidal anti-inflammatory drug (NSAID) used for treating pain, fever, and inflammation.',
    specifications: 'Conforms to IP/BP/USP standards. DC grades available.',
    applications: 'Formulated in tablets and capsules for anti-inflammatory and analgesic effects.',
    imageUrl: '/products/ibuprofen_pills.jpg',
  },
  {
    id: 'pregabalin',
    name: 'Pregabalin',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'An anticonvulsant and neuropathic pain–modulating agent that helps reduce abnormal nerve signaling, providing relief in conditions such as neuropathic pain, fibromyalgia, generalized anxiety disorder, and partial seizures.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Management of neuropathic pain, fibromyalgia, generalized anxiety disorder, and as an adjunctive therapy for partial seizures.',
    imageUrl: '/products/pregabalin-bottle.jpg',
  },
  {
    id: 'ritonavir',
    name: 'Ritonavir',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'An antiretroviral protease inhibitor primarily used as a pharmacokinetic enhancer (booster) in HIV treatment, increasing the effectiveness of other HIV medications by slowing their metabolism.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Used as a boosting agent in combination with other protease inhibitors for the treatment of HIV/AIDS.',
    imageUrl: '/products/ritonavir-pills.jpg',
  },
  {
    id: 'metformin-hcl',
    name: 'Metformin HCl',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A first-line antidiabetic agent from the biguanide class that improves insulin sensitivity, reduces hepatic glucose production, and supports glycemic control in patients with type 2 diabetes.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'First-line treatment for type 2 diabetes mellitus, particularly in overweight patients.',
    imageUrl: '/products/metformin-pills.jpg',
  },
  {
    id: 'propafenone-hcl',
    name: 'Propafenone HCl',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A Class IC antiarrhythmic agent used to restore and maintain normal heart rhythm by stabilizing cardiac electrical activity in conditions like atrial fibrillation and ventricular arrhythmias.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Treatment of life-threatening ventricular arrhythmias and maintenance of normal sinus rhythm in patients with symptomatic atrial fibrillation.',
    imageUrl: '/products/propafenone-hcl_pills.jpg',
  },
  {
    id: 'atorvastatin-calcium-trihydrate',
    name: 'Atorvastatin Calcium Trihydrate',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A lipid-lowering statin that reduces cholesterol synthesis, lowers LDL levels, and helps prevent cardiovascular complications such as heart attacks and strokes.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Used to lower cholesterol and triglycerides in the blood and to lower the risk of stroke, heart attack, and other heart complications.',
    imageUrl: '/products/atorvastatin-pills.jpg',
  },
  {
    id: 'nimorazole',
    name: 'Nimorazole',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A nitroimidazole-class antimicrobial agent effective against anaerobic bacteria and protozoa, commonly used for infections and as a radiosensitizer in cancer therapy.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Treatment of anaerobic infections and as a hypoxic radiosensitizer in the treatment of head and neck cancer.',
    imageUrl: '/products/nimorazole-pills.jpg',
  },
  {
    id: 'naftopidil',
    name: 'Naftopidil',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'An alpha-1 adrenergic receptor blocker that relaxes smooth muscles of the prostate and bladder neck, improving urinary flow in patients with benign prostatic hyperplasia (BPH).',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Treatment of the signs and symptoms of benign prostatic hyperplasia (BPH).',
    imageUrl: '/products/naftopidil-pills.jpg',
  },
  {
    id: 'meclizine-hcl',
    name: 'Meclizine HCl (Medizine HCl)',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'An antihistamine with antiemetic and antivertigo properties, widely used to reduce nausea, dizziness, and motion sickness by inhibiting vestibular system activity.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Prevention and treatment of nausea, vomiting, or dizziness associated with motion sickness and vertigo.',
    imageUrl: '/products/meclizine-pills.jpg',
  },
  {
    id: 'minoxidil',
    name: 'Minoxidil',
    category: 'Active Pharmaceutical Ingredients (APIs)',
    description: 'A potent vasodilator originally used as an antihypertensive, now primarily applied topically to stimulate hair growth by improving blood flow and prolonging the hair follicle growth phase.',
    specifications: 'Pharmaceutical grade, conforming to global standards.',
    applications: 'Topical treatment for androgenetic alopecia (male-pattern baldness) and as an oral medication for high blood pressure.',
    imageUrl: '/products/minoxidil.jpg',
  },
  {
    id: 'microcrystalline-cellulose',
    name: 'Microcrystalline Cellulose (MCC)',
    category: 'Excipients',
    description: 'A refined wood pulp, it is a white, free-flowing powder. Chemically, it is an inert substance, is not degraded during digestion and has no appreciable absorption.',
    specifications: 'Available in various grades (e.g., MCC 101, 102, 112) to suit different formulation needs.',
    applications: 'Used as a binder, diluent, disintegrant, and lubricant in tablet and capsule formulations.',
    imageUrl: '/products/excipient-product.jpg',
  },
    {
    id: 'croscarmellose-sodium',
    name: 'Croscarmellose Sodium',
    category: 'Excipients',
    description: 'An internally cross-linked sodium carboxymethylcellulose for use as a superdisintegrant in pharmaceutical formulations.',
    specifications: 'Conforms to Ph. Eur., USP/NF, and JP standards.',
    applications: 'Used in capsules, tablets, and granules to promote rapid disintegration.',
    imageUrl: '/products/excipient-powder.jpg',
  },
  {
    id: 'magnesium-stearate',
    name: 'Magnesium Stearate',
    category: 'Magnesium Stearate',
    description: 'A salt containing two equivalents of stearate and one magnesium cation. It is a fine white powder, insoluble in water.',
    specifications: 'Pharmaceutical grade, conforming to BP/USP standards. Vegetable and tallow-based options available.',
    applications: 'Widely used as a lubricant in the manufacture of tablets, capsules and powders to prevent ingredients from sticking to manufacturing equipment.',
    imageUrl: '/products/stearate-product.jpg',
  },
  {
    id: 'calcium-carbonate',
    name: 'Calcium Carbonate',
    category: 'Other Minerals',
    description: 'A chemical compound with the formula CaCO3. It is a common substance found in rocks as the minerals calcite and aragonite.',
    specifications: 'High-purity precipitated and ground grades available. Conforms to pharmaceutical standards.',
    applications: 'Used as a dietary calcium supplement, antacid, phosphate binder, or as a base material for pharmaceutical tablets.',
    imageUrl: '/products/mineral-product.jpg',
  },
  {
    id: 'aluminium-hydroxide',
    name: 'Aluminium Hydroxide',
    category: 'Antacids',
    description: 'An inorganic salt used as an antacid. It is a basic compound that neutralizes hydrochloric acid in the stomach.',
    specifications: 'Available as a dried gel powder or paste, conforming to IP/BP/USP monographs.',
    applications: 'A primary active ingredient in antacid formulations for the relief of heartburn, acid indigestion, and stomach upset.',
    imageUrl: '/products/antacid-powder.jpg',
  },
    {
    id: 'magnesium-hydroxide',
    name: 'Magnesium Hydroxide',
    category: 'Antacids',
    description: 'An inorganic compound with the chemical formula Mg(OH)2. It is often used as an antacid or a laxative.',
    specifications: 'High-purity pharmaceutical grade powder.',
    applications: 'Used in combination with aluminum hydroxide for fast-acting antacid relief, and at higher doses as an osmotic laxative.',
    imageUrl: '/products/magnesium-hydroxide-powder.jpg',
  },
];
